# Generated by Django 5.2.4 on 2025-10-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="temperature",
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="last_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="last_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="search_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="city",
            name="searched_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
